//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoSchoolAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaAlumno
    {
        public int IdMateriaAlumno { get; set; }
        public int Materia_IdMateria { get; set; }
        public int Alumnoes_IdAlumno { get; set; }
        public Nullable<float> Nota1 { get; set; }
        public Nullable<float> Nota2 { get; set; }
    
        public Alumnos Alumnos { get; set; }
        public Materias Materias { get; set; }
    }
}
