//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoSchoolAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaProfesors
    {
        public int IdMaterialProfesor { get; set; }
        public int IdProfesorFK { get; set; }
        public int Materias_IdMateria { get; set; }
    
        public virtual Materias Materias { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
