//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoSchool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SincoSchoolDBContainer : DbContext
    {
        public SincoSchoolDBContainer()
            : base("name=SincoSchoolDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<MateriaAlumno> MateriaAlumno { get; set; }
        public virtual DbSet<MateriaProfesors> MateriaProfesors { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
    }
}
